apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-demo
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
      
  - name: almalinux
    image: almalinux:9
    command: ["sh", "-c", "while true; do echo Hello Kubernetes! && sleep 3600; done"]
    volumeMounts:
     - mountPath: /mnt/nginx-logsD
       name: nginx-logs
       readOnly: true
  volumes:
  - name: nginx-logs
    emptyDir:
      sizeLimit: 100Mi   