apiVersion: v1 
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
    - name: nginx
      image: nginx
  resources:
    request:
     cpu: "60Mi" 
     memory: "100Mi" 
    
    limits:
     cpu: "100Mi"
     memory: "120Mi"