apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  ########### Replica set labels ###############
  labels: 
    purpose: headless-svc-demo
    project: roboshop
  
spec:
  replicas: 4
  selector:
  ######### These are used to select pods ##############
    matchLabels:
      ## purpose: dp-demo
      purpose: headless-svc-demo
      project: roboshop
### pod definition ########

  template:
    metadata:
      labels:
        purpose: headless-svc-demo
        project: roboshop
    spec:
      containers:
        - name: nginx
          image: nginx:latest
---
apiVersion: v1 
kind: Service
metadata:
    name: nginx
spec:    
    selector:
      purpose: headless-svc-demo
      project: roboshop
    ports:
    - protocol: TCP
      port: 80 ## service port
      targetPort: 80 ## container port

---
apiVersion: v1 
kind: Service
metadata:
 ## If a service clusterIP is set to None, it will be headless service, and it will not have a clusterIP, and it will not be load balanced, and it will not be accessible from outside the cluster, but it will be accessible from inside the cluster, and it will be used for stateful applications like databases, and it will be used for service discovery, and it will be used for internal communication between pods.
    name: nginx-headless
spec:
    clusterIP: None    
    selector:
      purpose: headless-svc-demo
      project: roboshop
    ports:
    - protocol: TCP
      port: 80 ## service port
      targetPort: 80 ## container port